controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
# config/routes.yaml
images:
    path: /images
    # the controller value has the format 'controller_class::method_name'
    controller: App\Controller\ImagesController::list

    # if the action is implemented as the __invoke() method of the
    # controller class, you can skip the '::method_name' part:
    # controller: App\Controller\BlogController